FROM node:22-alpine

WORKDIR /app

COPY backend/package.json backend/tsconfig.json ./
RUN npm install

COPY backend/prisma ./prisma
RUN npx prisma generate

COPY backend/src ./src

EXPOSE 3001

CMD ["npm", "run", "dev"]
